package com.rochanegra.api.finance.transactions;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;
import org.springframework.transaction.annotation.Transactional;

import com.rochanegra.api.exception.ResourceNotFoundException;
import com.rochanegra.api.finance.assets.Asset;
import com.rochanegra.api.finance.assets.AssetRepository;
import com.rochanegra.api.finance.assets.AssetService;
import com.rochanegra.api.finance.preferences.UserPreferencesService;
import com.rochanegra.api.finance.services.CurrencyConversionService;
import com.rochanegra.api.finance.types.TransactionType;

@Service
@RequiredArgsConstructor
public class TransactionService {

    private final TransactionRepository transactionRepository;
    private final AssetRepository assetRepository;
    private final AssetService assetService;
    private final CurrencyConversionService conversionService;
    private final UserPreferencesService preferencesService;

    @Transactional
    public List<TransactionDto> createTransactions(List<TransactionCreateDto> createDtos, UUID userId) {
        return createDtos.stream()
                .map(dto -> createTransaction(dto, userId))
                .collect(Collectors.toList());
    }

    public TransactionDto createTransaction(TransactionCreateDto createDto, UUID userId) {
        // 1. Get User's Base Currency for reporting
        String baseCurrency = preferencesService.getBaseCurrency(userId);
        TransactionType type = determineTransactionType(createDto); // (income, expense, transfer)

        // 2. Fetch the Primary Asset to understand the context
        Asset primaryAsset = assetRepository.findById(createDto.assetId())
                .orElseThrow(() -> new ResourceNotFoundException("Asset not found"));

        // 3. Determine the Exchange Rate to use
        // The rate we need is between the transaction's currency and the asset's
        // currency.
        BigDecimal rate = conversionService.getRate(createDto.currencyOriginal(), primaryAsset.getCurrency());

        // 4. Calculate the change in the ASSET's balance. This is the most important
        // calculation.
        // Example: Spent $10 USD (amountOriginal), rate is 0.92 EUR/USD, asset is in
        // EUR.
        // The asset's balance must change by -10.00 * 0.92 = -9.20 EUR.
        BigDecimal balanceChange = createDto.amountOriginal().multiply(rate);

        // 5. Update the Asset's balance
        primaryAsset.setCurrentValue(primaryAsset.getCurrentValue().add(balanceChange));
        assetRepository.save(primaryAsset);

        // 6. Handle Transfers
        if (createDto.destinationAssetId() != null) {
            // ... similar logic to update the destination asset's balance
        }

        // 7. For reporting, convert the original amount to the user's BASE currency.
        BigDecimal amountBase = conversionService.convert(
                createDto.amountOriginal(),
                createDto.currencyOriginal(),
                baseCurrency);

        Transaction transaction = new Transaction();
        transaction.setUserId(userId);
        transaction.setGeneratorId(null); // This is a manual, one-off transaction

        transaction.setAmountOriginal(createDto.amountOriginal());
        transaction.setCurrencyOriginal(createDto.currencyOriginal());
        transaction.setAmountBase(amountBase);
        transaction.setDescription(createDto.description());
        transaction.setExchangeRate(rate);
        transaction.setDate(createDto.date());
        transaction.setType(type);
        transaction.setCategoryId(createDto.categoryId());
        transaction.setAssetId(createDto.assetId());
        transaction.setDestinationAssetId(createDto.destinationAssetId());
        transaction.setAttachmentUrl(createDto.attachmentUrl());
        transaction.setCustomFields(createDto.customFields());

        Transaction savedTransaction = transactionRepository.save(transaction);

        if (createDto.assetId() != null) {
            assetService.updateBalance(createDto.assetId(), createDto.amountOriginal(), createDto.type());
        }

        return toDto(savedTransaction);
    }

    /**
     * NEW METHOD: Specifically for creating a transaction generated by the
     * scheduler.
     * It includes the generatorId to create the link.
     */
    @Transactional
    public TransactionDto createTransactionFromGenerator(TransactionCreateDto createDto, UUID generatorId,
            UUID userId) {

        // This method can now just call the main create method, after setting the
        // generatorId
        // This requires a bit of refactoring, but for now let's keep it simple:
        String baseCurrency = preferencesService.getBaseCurrency(userId);
        BigDecimal amountBase = conversionService.convert(createDto.amountOriginal(), createDto.currencyOriginal(),
                baseCurrency);

        Transaction transaction = new Transaction();
        transaction.setUserId(userId);
        transaction.setGeneratorId(generatorId);

        // Map fields from DTO (same as above)
        transaction.setAmountOriginal(createDto.amountOriginal());
        transaction.setCurrencyOriginal(createDto.currencyOriginal());
        transaction.setAmountBase(amountBase);
        transaction.setDescription(createDto.description());
        transaction.setDate(createDto.date());
        transaction.setType(createDto.type());
        transaction.setCategoryId(createDto.categoryId());
        transaction.setAssetId(createDto.assetId());
        transaction.setDestinationAssetId(createDto.destinationAssetId());

        Transaction savedTransaction = transactionRepository.save(transaction);

        // Here you would also add logic to UPDATE the associated Asset's balance
        // e.g., assetService.updateBalance(createDto.assetId(), createDto.amount());

        return toDto(savedTransaction);
    }

    public TransactionDto getTransaction(UUID id) {
        Transaction transaction = transactionRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Transaction not found"));
        return toDto(transaction);
    }

    public void deleteTransaction(UUID transactionId, UUID userId) {
        Transaction transaction = transactionRepository.findById(transactionId)
                .filter(tx -> tx.getUserId().equals(userId))
                .orElseThrow(() -> new ResourceNotFoundException("Transaction not found"));

        // Revert the balance changes by passing the negated amount
        updateBalancesForTransaction(transaction, true); // true = isReverting

        // Revert asset balance
        // if (transaction.getAssetId() != null) {
        // If it was income, we subtract. If expense, we add.
        // We can reuse updateBalance but invert the amount logic or type.
        // Simpler: pass NEGATED amount with SAME type.
        // updateBalance(income, -100) -> adds -100 = subtract 100.
        // updateBalance(expense, -100) -> subtracts -100 = adds 100.
        // assetService.updateBalance(transaction.getAssetId(),
        // transaction.getAmountOriginal().negate(),
        // transaction.getType());
        // }

        transactionRepository.delete(transaction);
    }

    public TransactionDto updateTransaction(UUID id, TransactionCreateDto updateDto) {
        Transaction transaction = transactionRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Transaction not found"));

        // Revert old asset balance
        if (transaction.getAssetId() != null) {
            assetService.updateBalance(transaction.getAssetId(), transaction.getAmountOriginal().negate(),
                    transaction.getType());
        }

        // Update fields
        if (updateDto.amountOriginal() != null)
            transaction.setAmountOriginal(updateDto.amountOriginal());
        if (updateDto.description() != null)
            transaction.setDescription(updateDto.description());
        if (updateDto.date() != null)
            transaction.setDate(updateDto.date());
        if (updateDto.type() != null)
            transaction.setType(updateDto.type()); // Careful if type changes logic
        if (updateDto.categoryId() != null)
            transaction.setCategoryId(updateDto.categoryId());

        // Asset ID Update logic is tricky if asset changes.
        // For now assuming asset is updated or kept.
        // But if updateDto.assetId() is passed (even transparently), we set it.
        // Assuming the DTO has all fields or partial? "TransactionCreateDto" is a
        // record with ALL fields.
        // If the user sends partial JSON, the record fields might be null.
        // But standard PATCH usually expects map or checked nulls.
        // Here we checked nulls.
        // However, if assetId is explicitly changed:
        if (updateDto.assetId() != null)
            transaction.setAssetId(updateDto.assetId());

        // Apply NEW asset balance
        if (transaction.getAssetId() != null) {
            assetService.updateBalance(transaction.getAssetId(), transaction.getAmountOriginal(),
                    transaction.getType());
        }

        Transaction saved = transactionRepository.save(transaction);
        return toDto(saved);
    }

    public org.springframework.data.domain.Page<TransactionDto> getTransactions(
            UUID userId,
            java.time.LocalDate startDate,
            java.time.LocalDate endDate,
            UUID categoryId,
            UUID assetId,
            org.springframework.data.domain.Pageable pageable) {

        org.springframework.data.jpa.domain.Specification<Transaction> spec = createSpecification(userId, startDate,
                endDate, categoryId, assetId);
        org.springframework.data.domain.Page<Transaction> page = transactionRepository.findAll(spec, pageable);
        return page.map(this::toDto);
    }

    // Deprecated or removed, kept for now if used elsewhere, but redirected to
    // filtered
    public List<TransactionDto> getTransactionsForUser(UUID userId) {
        return getTransactions(userId, null, null, null, null, org.springframework.data.domain.Pageable.unpaged())
                .getContent();
    }

    private org.springframework.data.jpa.domain.Specification<Transaction> createSpecification(
            UUID userId,
            java.time.LocalDate startDate,
            java.time.LocalDate endDate,
            UUID categoryId,
            UUID assetId) {
        return (root, query, criteriaBuilder) -> {
            java.util.List<jakarta.persistence.criteria.Predicate> predicates = new java.util.ArrayList<>();

            predicates.add(criteriaBuilder.equal(root.get("userId"), userId));

            if (startDate != null) {
                predicates.add(criteriaBuilder.greaterThanOrEqualTo(root.get("date"), startDate));
            }
            if (endDate != null) {
                predicates.add(criteriaBuilder.lessThanOrEqualTo(root.get("date"), endDate));
            }
            if (categoryId != null) {
                predicates.add(criteriaBuilder.equal(root.get("categoryId"), categoryId));
            }
            if (assetId != null) {
                predicates.add(criteriaBuilder.equal(root.get("assetId"), assetId));
            }

            return criteriaBuilder.and(predicates.toArray(new jakarta.persistence.criteria.Predicate[0]));
        };
    }

    private TransactionType determineTransactionType(TransactionCreateDto dto) {
        if (dto.destinationAssetId() != null) {
            return TransactionType.transfer;
        }
        // Amount can now be positive or negative from the DTO
        return dto.amountOriginal().signum() >= 0 ? TransactionType.income : TransactionType.expense;
    }

    // --- PRIVATE HELPER FOR BALANCE UPDATES ---
    private void updateBalancesForTransaction(Transaction transaction) {
        updateBalancesForTransaction(transaction, false);
    }

    private void updateBalancesForTransaction(Transaction transaction, boolean isReverting) {
        BigDecimal amount = transaction.getAmountBase(); // Always use the base amount for consistency
        if (isReverting) {
            amount = amount.negate();
        }

        // Update the primary asset
        if (transaction.getAssetId() != null) {
            Asset primaryAsset = assetRepository.findById(transaction.getAssetId()).orElseThrow();
            // We need to convert the base amount back to the asset's native currency
            BigDecimal changeInAssetCurrency = conversionService.convert(amount,
                    preferencesService.getBaseCurrency(transaction.getUserId()), primaryAsset.getCurrency());

            if (transaction.getType() == TransactionType.income) {
                primaryAsset.setCurrentValue(primaryAsset.getCurrentValue().add(changeInAssetCurrency));
            } else { // Expense or Transfer-out
                primaryAsset.setCurrentValue(primaryAsset.getCurrentValue().subtract(changeInAssetCurrency));
            }
            assetRepository.save(primaryAsset);
        }

        // Update destination asset for transfers
        if (transaction.getDestinationAssetId() != null) {
            Asset destAsset = assetRepository.findById(transaction.getDestinationAssetId()).orElseThrow();
            BigDecimal changeInDestCurrency = conversionService.convert(amount,
                    preferencesService.getBaseCurrency(transaction.getUserId()), destAsset.getCurrency());
            destAsset.setCurrentValue(destAsset.getCurrentValue().add(changeInDestCurrency)); // Always adds
            assetRepository.save(destAsset);
        }

        // You would add similar logic here for updating Liability balances if a
        // transaction is linked to one
    }

    private TransactionDto toDto(Transaction transaction) {
        return new TransactionDto(
                transaction.getId(),
                transaction.getGeneratorId(),
                transaction.getAmountOriginal(),
                transaction.getCurrencyOriginal(),
                transaction.getAmountBase(),
                transaction.getExchangeRate(),
                transaction.getDescription(),
                transaction.getDate(),
                transaction.getType(),
                transaction.getCategoryId(),
                transaction.getAssetId(),
                transaction.getDestinationAssetId(),
                transaction.getAttachmentUrl(),
                transaction.getCustomFields(),
                transaction.getCreatedAt(),
                transaction.getUpdatedAt());
    }
}